import Head from 'next/head'
import { useState } from 'react'
import Form from '../components/form.component'
import Location from '../components/location.component'
import Weather from '../components/weather.component'
import Screenshot from '../components/screenshot.component'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [trafficData, setTrafficData] = useState({location: "Bedok"});
  const [dateTime, setDateTime] = useState('');
  const [ss, setSS] = useState(null);
  const [geolocation, setGeolocation] = useState([]);

  const formResults = (formResults) => {
    setDateTime(formResults);
  }

  const settingScreenShot = (ss) => {
    setSS(ss)
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <Form formResults={formResults} />

        {/* Grid */}
        <div className={styles.grid}>
          <div className={`${styles.card} ${styles.location}`}>
            <h2>Location &darr;</h2>
            <Location dateTime={dateTime} settingScreenShot={settingScreenShot} trafficData={trafficData} setGeolocation={setGeolocation} />
          </div>
          <div className={`${styles.card} ${styles.weather}`}>
            <h2>Weather &darr;</h2>
            <Weather dateTime={dateTime} geolocation={geolocation} />
          </div>
        </div>

        <Screenshot ss={ss} />
        
      </main>
    </div>
  )
}
